### ISSUE TITLE
Are the signs inverted on rgb padding?

### ISSUE THREAD

**Issue by samedii** [google/mipnerf#18]
After the sigmoid activation I noticed that you are doing this
```
rgb = rgb * (1 + 2 * self.rgb_padding) - self.rgb_padding
```
where `rgb_padding = 0.001` by default.

Is this intentional or did you mean to move the range to `(rgb_padding, 1 - rgb_padding)`?

**Comment by jonbarron** [comment]
The range is intended to be (-0.001, 1.001).

**Comment by samedii** [comment]
Thanks for the quick response! :)
