### ISSUE TITLE
Need some suggestions for reimplementation in pytorch

### ISSUE THREAD

**Issue by chenghao-li-1029** [google/mipnerf#19]
Hi, thanks for this remarkable work. 

I'm trying to reimplement mipnerf in pytorch on LLFF. Currently, I've finished the pipeline identical to this repo. But the training converged to a lower psnr on the same validation images, e.g.  22.5 in my implementation vs 24.9 in this repo for 20w iterations . Is this phenomenon possibly caused by the natural of the optimizers in pytorch? Or maybe I missed some points in mipnerf implementation? Would you please provide some suggestions? 

Thank you!

**Comment by hjxwhy** [comment]
My pytorch replicate result is also lower than paper but my best val result is 29.9.
