### ISSUE TITLE
IPE explained

### ISSUE THREAD

**Issue by theFilipko** [google/mipnerf#22]
Hello. 
First of all, thank you for sharing this great work.

I would like to kindly ask you to elaborate more on how did you derive the formulas for IPE. 

Why do you concatenate it this way?
![image](https://user-images.githubusercontent.com/26874096/167145554-bb3c1499-c692-4b0c-9ca7-733a9a014fd2.png)

How did you get the formula for the `y_var`?
![image](https://user-images.githubusercontent.com/26874096/167145906-d16f033a-d034-4954-a5c9-46f239ebf56a.png)

I cannot quiet get it from the article.
Thank you :)

**Comment by jonbarron** [comment]
expected_sin() is just the expectation of sin() with respect to a normal distribution, you can re-derive it using Mathematica or something by integrating the product of a normal distribution and sin(x). That concatenation of sin(x) and sin(x + pi/2) is just a way of computing sin(x) and cos(x) quickly, as cos(x) = sin(x+pi/2).

**Comment by theFilipko** [comment]
Thank you for the explanation :)

**Comment by theFilipko** [comment]
Why do you omit `y_var` returned by the `expected_sin` in IPE?
https://github.com/google/mipnerf/blob/main/internal/mip.py#L182-L184

**Comment by jonbarron** [comment]
We don't use `y_var` anywhere in the algorithm. It's only computed in the code because I thought someone might find it useful some day.
