### ISSUE TITLE
Radii computation with and without NDC

### ISSUE THREAD

**Issue by NagabhushanSN95** [google/mipnerf#31]
The `radii` computation code is different for non-ndc and ndc spaces. In particular, without ndc, `radii` computation uses only `dx` derived from `directions`, but when ndc is enabled, `(dx+dy)/2` is used, which is derived from `ndc_origins`. Can you please shed some light on why it is done so?

**Comment by jonbarron** [comment]
I think this is an oversight on our part. I doubt it matters, they're both valid choices, and dy and dx should always be pretty similar values.

**Comment by jonbarron** [comment]
Please let me know if performance is very sensitive to dx vs (dx+dy)/2, that would be interesting!

**Comment by NagabhushanSN95** [comment]
Okay. Thanks for the clarification. In case I test it out, I'll update here :)
