### ISSUE TITLE
Why the training time is longer than NeRF

### ISSUE THREAD

**Issue by Harperrrr111** [google/mipnerf#34]
Hi, It seems that mip-NeRF takes much longer time to train compared to NeRF. Is there any explanation or comparison?  Thanks!

**Comment by jonbarron** [comment]
Hi, I'll need more information to advise. With the same model size and batch size, and running on the same accelerator, mip-NeRF should be comparable to or slightly faster than a vanilla NeRF implementation. If it's much longer you probably have a bug somewhere.

**Comment by Harperrrr111** [comment]
Thanks for your reply. I tested again carefully and found you are right. My mistake was caused by a different setting.

BTW, It seems that mip-NeRF need more GPU memory during training. I want to ask  why and if it is possible to address this problem?

**Comment by jonbarron** [comment]
mip-NeRF does more math than NeRF when ray-casting (points along the ray have sizes / covariance matrices associated with them) so it should take more memory.

**Comment by Harperrrr111** [comment]
Many thanks for answering.
