### ISSUE TITLE
Tiny typo in supplemental material

### ISSUE THREAD

**Issue by Leviosaaaa** [google/mipnerf#37]
Hi! Thanks for sharing the great work! 

I was just going through the paper and might find a tiny typo. So I am posting an issue in case you did not already notice. In the 1st section of supplemental material, I guess it should be `(sinθ)^2` here instead of  `sinθ`.

![Screen_2022-09-15_15-40-57](https://user-images.githubusercontent.com/61225697/190346376-2b37c11c-1326-42a3-b064-5d6944020a3f.png)

**Comment by jonbarron** [comment]
Oops, nice catch! Thanks for the heads up.
