### ISSUE TITLE
origins and directions issues

### ISSUE THREAD

**Issue by haiz20060684** [google/mipnerf#38]
hi,thanks for your exciting work.I have one question.
In the code,the initialization values of directions are (x,y,1),so i think the values of origins should be (x,y,0).So,the values of directions are Xdirections=R*Xc+t,the values of origins are Xdirections-R[0:3,2].

**Comment by jonbarron** [comment]
Sorry, I don't understand your question.

**Comment by haiz20060684** [comment]
In the paper,the distance of origin and direction is 1.In the code,the initialization image coordinate values of directions are [0.5...,0.5...,1],so the world coordinate values of directions should be R*Kinverse*X+t,but R*Kinverse*X.
