### ISSUE TITLE
Reconstructing using colmap poses

### ISSUE THREAD

**Issue by nishant34** [google/mipnerf#9]
If we estimate the poses of the  lego dataset using colmap, will it work? I tried doing the same, and tried training it using train_llff.sh but it showed inconsistent results.

**Comment by jonbarron** [comment]
Colmap should be able to reconstruct the poses from the lego dataset, but I definitely wouldn't use the LLFF dataloader and parameters. The LLFF loader assumes that you're looking at a "front facing" scene, which is definitely not the case for the Blender data. 

You probably want to use the blender code path and data loader, and write your own modification for getting the colmap cameras into the blender format.

**Comment by nishant34** [comment]
Yeah, I totally agree with you, but I don't know how to align the blender and colmap poses, which when plotted appear to be sufficiently different.
